### ISSUE TITLE
Exception: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by drallgood** [octopress/asset-pipeline#11]
```
/Library/Ruby/Gems/2.0.0/gems/octopress-ink-1.0.0.rc.48/lib/octopress-ink/plugin.rb:31:in `join': no implicit conversion of nil into String (TypeError)
	from /Library/Ruby/Gems/2.0.0/gems/octopress-ink-1.0.0.rc.48/lib/octopress-ink/plugin.rb:31:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/octopress-ink-1.0.0.rc.48/lib/octopress-ink/plugins.rb:80:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/octopress-ink-1.0.0.rc.48/lib/octopress-ink/plugins.rb:80:in `register_plugin'
	from /Library/Ruby/Gems/2.0.0/gems/octopress-ink-1.0.0.rc.48/lib/octopress-ink.rb:75:in `register_plugin'
	from /Library/Ruby/Gems/2.0.0/gems/octopress-asset-pipeline-2.0.2/lib/octopress-asset-pipeline.rb:163:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:76:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:72:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:72:in `block in require'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:61:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:61:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.7.12/lib/bundler.rb:134:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:38:in `require_from_bundler'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/bin/jekyll:16:in `<top (required)>'
	from /usr/bin/jekyll:23:in `load'
	from /usr/bin/jekyll:23:in `<main>'
```

**Comment by imathis** [comment]
Can you tell me what Octopress Ink plugins you have? Do you have any that you've written?

**Comment by drallgood** [comment]
Nope. Not at the moment.

Here's my Gemfile:
```
group :jekyll_plugins do
  #gem 'octopress-pullquote-tag'
  gem "jekyll-compass", "~> 1.0.5"
  gem 'octopress-multilingual'
  gem 'octopress-feeds'
  gem 'octopress-quote-tag'
  gem 'octopress-asset-pipeline'
  gem 'octopress-date-format'
  gem 'octopress-codeblock'
  gem 'octopress-gist'
  gem 'octopress-codefence'
  gem 'octopress-return-tag'
  gem 'octopress-filters'
  gem 'octopress-linkblog'
  #gem 'octopress-categories', :git => 'https://github.com/octopress/category-index'
  #gem 'octopress-paginate'
end
```

**Comment by imathis** [comment]
I suspect the categories thing is the problem. I don't know if it's master branch is compatible with the latest Octopress Ink. I don't recommend using master as a stable gem.

**Comment by imathis** [comment]
And I just saw that you have it commented out… so… I'll see what it is about.

**Comment by drallgood** [comment]
Yeah.. I commented that one out so it doesn't interfere...
And the other ones that are currently commented out are broken ;)

**Comment by chauncey-garrett** [comment]
@imathis I'm seeing this too on `octopress-ink.rc.50`.

Here's my current Jekyll plugins:

```
group :jekyll_plugins do

  # Sitemap
  gem 'jekyll-sitemap'

  # amazon plugin
  gem 'amazon-ecs'
  gem 'i18n'

  # speed up LSI
  # gem 'narray', :git => "https://github.com/tonyarnold/narray"
  # gem 'gsl', :git => "https://github.com/tonyarnold/rb-gsl"

  # redirect URLs
  gem 'jekyll-redirect-from', '~> 0.6'

  # archives page
  gem 'jekyll-archives'

  #
  # Octopress
  #

  gem 'octopress', '~> 3.0.0.rc'

  # asset pipeline for CSS and JS
  gem 'octopress-asset-pipeline'

  # ink
  gem 'octopress-ink'

  # code highlighting
  gem 'octopress-codefence'
  gem 'octopress-solarized'
  gem 'octopress-escape-code'

  # linkblog
  gem 'octopress-linkblog'
  gem 'octopress-quote-tag'
  gem 'octopress-pullquote-tag'

  # date formatting
  gem 'octopress-date-format'
  gem 'octopress-filters'

  # tag rendering
  gem 'octopress-render-tag'

  # feeds
  gem 'octopress-feeds'

  # videos
  gem 'octopress-video-tag'

end
```

**Comment by mdotasia** [comment]
I get the same error with `octopress-ink.rc.50`. My gems:

```
  spec.add_runtime_dependency 'octopress-asset-pipeline', '~> 2.0.2'
  spec.add_runtime_dependency 'octopress-comment-tag', '~> 1.0.1'
  spec.add_runtime_dependency 'octopress-ink', '~> 1.0.0.rc.50'
  spec.add_runtime_dependency 'octopress-render-tag', '~> 1.0.6'
  spec.add_runtime_dependency 'jekyll-sitemap', '~> 0.8.0'
```

**Comment by imathis** [comment]
Thanks y'all. I'll look into this tonight. I'm sorry for the hassle.

**Comment by imathis** [comment]
I've update octopress-asset-pipeline, octopress-feeds and octopress-ink and I believe this issue should be sorted. Try to run `bundle update` and let me know if this issue has been resolved.
