### ISSUE TITLE
Unable to activate octopress-asset-pipeline-2.0.6, because octopress-ink-1.2.0 conflicts with octopress-ink (~> 1.1.0 ) (Gem::ConflictError)

### ISSUE THREAD

**Issue by e9t** [octopress/asset-pipeline#19]
I'm getting dependency version mismatches with `octopress-ink`, and this makes `asset-pipeline` to fail.

<pre>
$ octopress ink copy solarized --config
/Library/Ruby/Site/2.0.0/rubygems/specification.rb:2112:in `raise_if_conflicts': Unable to activate octopress-asset-pipeline-2.0.6, because octopress-ink-1.2.0 conflicts with octopress-ink (~> 1.1.0
) (Gem::ConflictError)
        from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1280:in `activate'
        from /Library/Ruby/Site/2.0.0/rubygems.rb:198:in `rescue in try_activate'
        from /Library/Ruby/Site/2.0.0/rubygems.rb:195:in `try_activate'
        from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
        from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `block in require_gems'
        from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `each'
        from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `require_gems'
        from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
        from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:79:in `setup'
        from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:41:in `initialize'
        from /Library/Ruby/Gems/2.0.0/gems/octopress-3.0.11/lib/octopress.rb:68:in `new'
        from /Library/Ruby/Gems/2.0.0/gems/octopress-3.0.11/lib/octopress.rb:68:in `read_site'
        from /Library/Ruby/Gems/2.0.0/gems/octopress-3.0.11/lib/octopress.rb:61:in `site'
        from /Library/Ruby/Gems/2.0.0/gems/octopress-ink-1.2.0/lib/octopress-ink.rb:164:in `copy_plugin_assets'
        from /Library/Ruby/Gems/2.0.0/gems/octopress-ink-1.2.0/lib/octopress-ink/commands/copy.rb:20:in `block (2 levels) in process_command'
        from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from /Library/Ruby/Gems/2.0.0/gems/octopress-3.0.11/bin/octopress:8:in `<top (required)>'
        from /usr/bin/octopress:23:in `load'
        from /usr/bin/octopress:23:in `<main>'
</pre>

- Excerpt from `Gemfile.lock`

<pre>
    ...
    octopress (3.0.11)
      jekyll (>= 2.0)
      mercenary (~> 0.3.2)
      octopress-deploy
      octopress-escape-code (~> 2.0)
      octopress-hooks (~> 2.0)
      redcarpet (~> 3.0)
      titlecase
    octopress-asset-pipeline (2.0.6)
      octopress-ink (~> 1.1.0)
    octopress-autoprefixer (1.0.1)
      autoprefixer-rails (~> 2.2)
      jekyll (>= 2.0)
      octopress-hooks (~> 2.0)
    octopress-code-highlighter (4.2.6)
      colorator (~> 0.1)
      octopress-hooks
    octopress-codeblock (1.0.5)
      octopress-code-highlighter (~> 4.2)
    octopress-codefence (1.6.1)
      octopress-code-highlighter (~> 4.2)
      octopress-hooks (~> 2.1)
    octopress-date-format (3.0.3)
      jekyll (>= 2.0)
    octopress-deploy (1.3.0)
      colorator
    octopress-escape-code (2.0.6)
      octopress-hooks (~> 2.0)
    octopress-feeds (2.0.4)
      octopress-date-format
      octopress-ink (~> 1.0)
      octopress-return-tag
    octopress-filters (1.3.3)
      jekyll
      octopress-hooks (~> 2.0)
      rubypants-unicode
      titlecase
    octopress-gist (1.3.5)
      octopress-code-highlighter (~> 4.2)
    octopress-hooks (2.6.1)
      jekyll (>= 2.0)
    octopress-image-tag (1.1.0)
      jekyll
    octopress-include-tag (1.1.3)
      jekyll (>= 2.0)
      octopress-tag-helpers (~> 1.0)
    octopress-ink (1.1.4)
      jekyll (>= 2.0)
      octopress (~> 3.0)
      octopress-autoprefixer
      octopress-date-format
      octopress-filters (~> 1.1)
      octopress-hooks (~> 2.2)
      octopress-include-tag (~> 1.0)
      uglifier (~> 2.5)
    octopress-minify-html (1.3.0)
      html_press (~> 0.8)
      jekyll (>= 2.0)
      octopress-hooks
    octopress-multilingual (1.2.0)
      octopress-hooks
    octopress-paginate (1.1.2)
      octopress-hooks
    octopress-return-tag (1.0.1)
      jekyll
      octopress-tag-helpers (~> 1.0)
    octopress-solarized (1.1.2)
      octopress-ink (~> 1.0)
    octopress-tag-helpers (1.0.8)
      jekyll (>= 2.0)
    ...
</pre>

I've tried `bundle update`, but no success. Is there anything else I can try?

**Comment by e9t** [comment]
Forcing `gem 'jekyll', '< 3.0.0'` made this issue go away.
Closing this issue for the moment.
